build:
  verbosity: detailed
  project: FolderDifferenceDetector\FolderDifferenceDetector.sln
  
configuration: Release

deploy:
  release: FolderDifferenceDetector-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: cxiHYFfint9KkR184q7kzHfxk4WEvRo6QG6IGZ+emXCOviMV/3mOQJqmDxKjIh4e
  draft: false
  prerelease: false
  on:
    branch: release
artifacts: 
  - path: FolderDifferenceDetector\FolderDifferenceDetector\bin\Release\FolderDifferenceDetector.exe
skip_tags: true